### ISSUE TITLE
no wheel release

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [flake8-commas/flake8-commas#11]
this is a pure python package, so a wheel would speed up installs and ease/speed up use in ci settings

it should be a matter of adding a bdist_wheel step before the upload \* configuring for universal wheels

**Comment by graingert** [comment]
fixed in https://github.com/zedlander/flake8-commas/pull/9

@zedlander ping

**Comment by zedlander** [comment]
Ok this should be fixed now in version 0.1.6. It's my first time deploying a wheel so let me know if it works properly for you guys. Thanks @graingert for the PR :)

**Comment by graingert** [comment]
Fixed in 0.2.0
