### ISSUE TITLE
Ability to enforce no trailing commas

### ISSUE THREAD

**Issue by kvdb** [flake8-commas/flake8-commas#22]
Enforcing a consistent coding style is what I'm after. I understand the reason for enforcing trailing commas, but I prefer not having trailing commas - just a personal preference. I'd like to consistently apply the chosen style. Therefore, it'd be great if flake8-commas could enforce either style as a setting.

**Comment by graingert** [comment]
@kvdb how do you avoid annoying merge conflicts on dictionary, list and function call diffs?

**Comment by graingert** [comment]
@kvdb Personally I would have no use for a feature to ban trailing commas, it leads to odd code like:

```python
foo = {
    'ham': 'spam'
    ,'eggs': 'toast'
    ,'beans': 'bacon'
}
```

You're welcome to create a fork, and or make the code in this repo publicly exportable for another plugins' use.

**Comment by kvdb** [comment]
@graingert, perhaps I explained it a bit different, but this is how my code looks:

    foo = {
        'ham': 'spam',
        'eggs': 'toast',
        'beans': 'bacon'
    }

In practice I don't encounter a lot of merge conflict because of this coding style.
Another plugin might be the best solution indeed.
