### ISSUE TITLE
False positives for multiline strings

### ISSUE THREAD

**Issue by phihag** [flake8-commas/flake8-commas#23]
I have a file with the content

    s = (
        'this' +
        'is a string'
    )
    print(s)

and another with

    s = (
        'this'
        'is a string'
    )
    print(s)

Both files emit a warning

    t.py:3:18: C812 missing trailing comma

This warning **dangerous**, since actually adding a comma changes the meaning of the statement!

**Comment by graingert** [comment]
@phihag fixed in 0.2.0

**Comment by bear24rw** [comment]
Would it be possible to add an optional check to flag multiline strings as errors? In my code base we never use multiline strings and I would like to catch missing commas in lists.
