### ISSUE TITLE
trailing *args should not require comma

### ISSUE THREAD

**Issue by graingert** [flake8-commas/flake8-commas#27]
```python
result = function(
    foo,
    bar,
    *args
)
```

**Comment by PeterJCLaw** [comment]
Given that it's valid in Python 3 to do, for example:
``` python
result = function(
    foo,
    bar,
    *args,
    more,
)
```
I'd quite like to require a comma after the splat here. Would you be open to changing that?

**Comment by graingert** [comment]
@PeterJCLaw can you create a issue for that?

**Comment by PeterJCLaw** [comment]
https://github.com/PyCQA/flake8-commas/issues/62
