### ISSUE TITLE
print statement + string literal concatenation produces

### ISSUE THREAD

**Issue by janrito** [flake8-commas/flake8-commas#36]
I think flake8-commas is getting confused between python 3's print function and python 2's print statement followed by a concatenated string literal.

This is valid python code: 
```
print (
    "abcdefghijklmnopqrstuvwxyz"
    "zyxwvutsrqponmlkjihgfedcba"
)
```
see: https://docs.python.org/2/reference/lexical_analysis.html#string-literal-concatenation

It is equivalent to:

```
print "abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba"
```

However, Flake8-commas produces the warning:

```
C813 missing trailing comma in Python 3
```

Adding a trailing comma to the end of the concatenated string literal turns the statement into a tuple. Equivalent to this:

```
print ("abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba", )
```

Which is not the same thing.

**Updated***

**Comment by iafilatov** [comment]
Same with `assert`.
```python
assert (
    False
)
```
produces C812 but you can't have a comma there.

**Comment by tolomea** [comment]
There seems to be a general issue with  string concatenation, like this

.\manage.py:19:60: C812 missing trailing comma

            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )

**Comment by iafilatov** [comment]
@tolomea  That's one arg on a separate line which technically requires a comma. it does seem a bit off because the primary _intention_ is to use parenthesis for grouping (even though the syntax requires them anyway). There's a PR #38 that allows to disable warnings for such forms when there's only one arg.

**Comment by graingert** [comment]
`C813 missing trailing comma in Python 3`

This means that if you're running your code in Python 2, you should not heed those errors.

In python 3 you need a trailing comma

```python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print (
...     "abcdefghijklmnopqrstuvwxyz"
...     "zyxwvutsrqponmlkjihgfedcba"
... )
abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba
>>> print ("abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba", )
abcdefghijklmnopqrstuvwxyzzyxwvutsrqponmlkjihgfedcba
>>> 
```
